# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
pro: true
project_name: sponsors

metadata:
  description: "Fetches sponsors from multiple sources and renders them based on templates"
  license: MIT
  homepage: https://goreleaser.com/sponsors

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
universal_binaries:
  - replace: false

source:
  enabled: true
  name_template: "{{ .ProjectName }}.src"

archives:
  - formats: [tar.gz]
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mtime: "{{ .CommitTimestamp }}"

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

checksum:
  name_template: "checksums.txt"

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

homebrew_casks:
  - repository:
      owner: goreleaser
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"
    url:
      verified: github.com/goreleaser/sponsors/releases/download

npms:
  - name: "@goreleaser/sponsors"
    repository: https://github.com/goreleaser/sponsors
    bugs: https://github.com/goreleaser/mcp/sponsors
    keywords:
      - goreleaser
      - sponsors
